# Generated by Django 5.0.3 on 2024-03-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mizuki_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Mizuki_app.product'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
