# Generated by Django 5.0.3 on 2024-03-10 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mizuki_app', '0002_order_products_delete_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mizuki_app.order')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mizuki_app.product')),
            ],
        ),
    ]
