# Generated by Django 5.0.3 on 2024-03-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mizuki_app', '0003_remove_order_products_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='tableNumber',
            field=models.PositiveIntegerField(default=33, verbose_name='Numero de mesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='waitingPayment',
            field=models.BooleanField(default=False, verbose_name='Orden por cobrar'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='Mizuki_app.categories'),
            preserve_default=False,
        ),
    ]
